apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-optimization.fullname" . }}-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: k8s-optimization
    app.kubernetes.io/part-of: k8s-optimization
    control-plane: controller-manager
  {{- include "k8s-optimization.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "k8s-optimization.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}