{{- /*
Copyright 2021 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudhealth-collector.fullname" . }}
  labels:
    {{- include "cloudhealth-collector.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudhealth-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cloudhealth-collector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
