{{- /*
Copyright 2021 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudhealth-collector.secret.name" . }}
  labels:
    {{- include "cloudhealth-collector.labels" . | nindent 4 }}
type: Opaque
data:
  apiToken:  {{ .Values.apiToken | b64enc | quote }}
  clusterName: {{ .Values.clusterName | b64enc | quote }}
{{- end }}
