# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudhealth-collector.serviceAccountName" . }}
  labels:
    {{- include "cloudhealth-collector.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
