# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ch-agent.fullname" . }}
  labels:
    {{- include "ch-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - "pods"
    - "nodes"
    - "services"
    - "namespaces"
  verbs: ["get", "watch", "list"]
