# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudhealth-collector
  labels:
    app: cloudhealth-collector
subjects:
- kind: ServiceAccount
  name: cloudhealth-collector
  namespace: default
roleRef:
  kind: ClusterRole
  name: cloudhealth-collector
  apiGroup: rbac.authorization.k8s.io
