# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ch-agent.fullname" . }}
  labels:
    {{- include "ch-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ch-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ch-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ch-agent.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CHT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudhealth-config
                  key: api-token
            - name: CHT_CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudhealth-config
                  key: cluster-name
            - name: CHT_INTERVAL
              value: "900"
            - name: CHT_JVM_MEM
              value: "-Xmx891M"
          args: ["upload_k8s_state", "--verbose"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
