# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudhealth-collector
  labels:
    app: cloudhealth-collector
automountServiceAccountToken: true